spring:
   data:
      mongodb:
         database: pasaporteapi
         field-naming-strategy:
         grid-fs-database:
         host: localhost
         port: 27017         
         repositories:
            enabled: true
         